'use strict';

const API_URL =
  window.STEAMSCOPE_CONFIG?.apiUrl ||
  'http://localhost:7071/api/stats'; // fallback for local dev

const INSIGHTS_URL = API_URL.replace('/stats', '/insights');

function fmt(iso) {
  return new Date(iso).toLocaleString(undefined, {
    month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function gameIcon(g) {
  return g.iconUrl
    ? `<img class="game-icon" src="${g.iconUrl}" alt="${g.name}" loading="lazy" />`
    : `<div class="game-icon" style="display:flex;align-items:center;justify-content:center;font-size:1.4rem;">🎮</div>`;
}

function parseInsightSections(markdown) {
  const sections = [];
  const parts = ('\n' + markdown.replace(/\r/g, '')).split('\n## ');
  for (const part of parts) {
    if (!part.trim()) continue;
    const nl      = part.indexOf('\n');
    const heading = (nl === -1 ? part : part.slice(0, nl)).trim();
    const body    = (nl === -1 ? '' : part.slice(nl + 1)).trim();
    if (heading) sections.push({ heading, body });
  }
  return sections;
}

function insightBodyHtml(text) {
  const lines = text.split('\n').filter(l => l.trim());
  let html = '', inList = false;
  for (const line of lines) {
    if (line.startsWith('- ')) {
      if (!inList) { html += '<ul class="insight-list">'; inList = true; }
      html += `<li>${line.slice(2)}</li>`;
    } else {
      if (inList) { html += '</ul>'; inList = false; }
      html += `<p>${line}</p>`;
    }
  }
  if (inList) html += '</ul>';
  return html;
}

function renderInsightsHTML(insights) {
  const header = `<div class="section-header">AI Gaming Insights</div>`;

  if (!insights || insights.error) {
    return header + `
      <div class="insights-unavailable">
        <p>${insights?.error || 'Insights unavailable.'}</p>
      </div>`;
  }

  const sections = parseInsightSections(insights.insights);
  const last     = sections.length - 1;
  const cards    = sections.map((s, i) => `
    <div class="insight-card${i === last ? ' insight-card--full' : ''}">
      <div class="insight-card-title">${s.heading}</div>
      <div class="insight-body">${insightBodyHtml(s.body)}</div>
    </div>
  `).join('');

  const time = new Date(insights.generatedAt).toLocaleTimeString(undefined, {
    hour: '2-digit', minute: '2-digit',
  });

  return header +
    `<div class="insights-grid">${cards}</div>` +
    `<div class="insights-footer">Generated by ${insights.model} &middot; ${time}</div>`;
}

function render(data) {
  const { player, library, recentlyPlayed, fetchedAt } = data;
  const maxHours = library.topGames[0]?.playtimeHours || 1;

  document.getElementById('root').innerHTML = `
    <header class="header">
      <div class="logo">SteamScope</div>
      <div class="last-updated">Synced ${fmt(fetchedAt)}</div>
    </header>

    <div class="container">

      <div class="profile-card">
        <img class="avatar" src="${player.avatarFull}" alt="${player.name}" />
        <div class="profile-info">
          <div class="profile-name">
            <span class="status-dot ${player.isOnline ? '' : 'offline'}"></span>
            ${player.name}
            ${player.realName ? `<span class="real-name">· ${player.realName}</span>` : ''}
          </div>
          <a class="profile-link" href="${player.profileUrl}" target="_blank" rel="noopener">
            View on Steam →
          </a>
        </div>
      </div>

      <div class="stats-row">
        <div class="stat-card">
          <div class="stat-label">Games Owned</div>
          <div class="stat-value">${library.totalGames}<span class="unit">games</span></div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Total Playtime</div>
          <div class="stat-value">${library.totalPlaytimeHours}<span class="unit">hrs</span></div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Played Recently</div>
          <div class="stat-value">${recentlyPlayed.totalCount}<span class="unit">games</span></div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Most Played</div>
          <div class="stat-top-game">${library.topGames[0]?.name ?? '—'}</div>
        </div>
      </div>

      <div class="section">
        <div class="section-header">Recently Played &mdash; Last 2 Weeks</div>
        <div class="recent-grid">
          ${recentlyPlayed.games.map(g => `
            <div class="recent-game">
              ${g.iconUrl
                ? `<img src="${g.iconUrl}" alt="${g.name}" loading="lazy" />`
                : `<div style="width:64px;height:64px;border-radius:6px;background:#1f2937;display:flex;align-items:center;justify-content:center;font-size:1.8rem;">🎮</div>`
              }
              <div class="recent-game-name">${g.name}</div>
              <div class="recent-time">${g.playtime2WeeksHours}h this week</div>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="section">
        <div class="section-header">Top Games by Total Playtime</div>
        ${library.topGames.map(g => `
          <div class="game-row">
            ${gameIcon(g)}
            <div class="game-info">
              <div class="game-name">${g.name}</div>
              <div class="bar-wrap">
                <div class="bar" style="width:${Math.round((g.playtimeHours / maxHours) * 100)}%"></div>
              </div>
            </div>
            <div class="game-hours">${g.playtimeHours} hrs</div>
          </div>
        `).join('')}
      </div>

      <div id="insights-section" class="section">
        <div class="section-header">AI Gaming Insights</div>
        <div class="insights-loading-state">
          <div class="splash-spinner"></div>
          <p>Generating insights&hellip;</p>
        </div>
      </div>

    </div>
  `;
}

async function load() {
  // Kick off both fetches immediately so insights load in parallel
  const statsPromise = fetch(API_URL);
  const insightsPromise = fetch(INSIGHTS_URL)
    .then(r => r.json())
    .catch(() => null);

  try {
    const statsRes = await statsPromise;
    if (!statsRes.ok) throw new Error(`HTTP ${statsRes.status}`);
    const data = await statsRes.json();
    if (data.error) throw new Error(data.error);
    render(data);

    // Fill insights section once Claude responds (non-blocking for stats)
    const insights = await insightsPromise;
    document.getElementById('insights-section').innerHTML = renderInsightsHTML(insights);
  } catch (err) {
    document.getElementById('root').innerHTML = `
      <div class="splash">
        <p class="error-msg">Failed to load: ${err.message}</p>
        <button class="retry-btn" onclick="load()">Retry</button>
      </div>`;
  }
}

load();
